//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<bool> ShowInTreeview { get; set; }
        public string ClientName { get; set; }
        public string LegalName { get; set; }
        public string ClientCode { get; set; }
        public Nullable<int> ClientType { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ParentType { get; set; }
        public string EIN { get; set; }
        public Nullable<int> ARBasis { get; set; }
        public Nullable<int> APBasis { get; set; }
        public Nullable<int> APGLAccountID { get; set; }
        public Nullable<int> FYStartMonth { get; set; }
        public Nullable<int> LastPaymentGLAccountID { get; set; }
        public Nullable<int> StatementLayoutID { get; set; }
        public Nullable<bool> UseDefaultStatementSettings { get; set; }
        public Nullable<bool> CombineTAccts { get; set; }
        public Nullable<bool> GroupSubTotal { get; set; }
        public Nullable<bool> ZeroBalanceStatements { get; set; }
        public Nullable<bool> ACHStatements { get; set; }
        public string StatementNote { get; set; }
        public Nullable<int> StatementFrequency { get; set; }
        public Nullable<int> StatementDay { get; set; }
        public Nullable<int> StatementLateDays { get; set; }
        public Nullable<decimal> StatementLateFee { get; set; }
        public Nullable<bool> CostCenters { get; set; }
        public Nullable<int> ForceBudgetedGL { get; set; }
        public Nullable<int> NPComplianceID { get; set; }
        public Nullable<int> NPDelinquencyID { get; set; }
        public Nullable<int> xID { get; set; }
        public Nullable<int> RetainedEarningsGLAccountID { get; set; }
        public Nullable<bool> UsePriorAccountNumbers { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string CollectionPolicy { get; set; }
        public Nullable<int> AppliedPaymentSortType { get; set; }
        public string Active { get; set; }
        public Nullable<bool> AccountNumbersRun { get; set; }
        public Nullable<bool> IsTrainingClient { get; set; }
        public Nullable<decimal> WorkingCapital { get; set; }
        public Nullable<bool> UseCaliberWeb { get; set; }
        public Nullable<bool> EnableCentralDisbursing { get; set; }
        public Nullable<int> LastPaymentCCID { get; set; }
        public Nullable<decimal> StatementLateFeePercentage { get; set; }
        public Nullable<byte> StatementLateFeeType { get; set; }
        public Nullable<bool> UseSpecifiedRemitAddress { get; set; }
        public Nullable<int> ReserveRetainedEarningsGLAccountID { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string ACHDescription { get; set; }
        public Nullable<int> MaxUnits { get; set; }
        public string APGLSetting { get; set; }
        public Nullable<int> MainModule { get; set; }
        public Nullable<int> iColligoAssociationID { get; set; }
        public string iColligoAuthCode { get; set; }
        public Nullable<bool> OverrideDefaultWOTemplate { get; set; }
        public Nullable<int> OverrideTemplateID { get; set; }
    }
}
