//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRErrorLogger
    {
        public string LogID { get; set; }
        public string ErrorMessage { get; set; }
        public string Stacktrace { get; set; }
        public System.DateTime Date { get; set; }
        public string InnerException { get; set; }
        public string ErrorLevel { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
    }
}
