//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRPropertyManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRPropertyManager()
        {
            this.PRProperties = new HashSet<PRProperty>();
            this.PRRenewals = new HashSet<PRRenewal>();
            this.PRUnits = new HashSet<PRUnit>();
            this.PRUsers = new HashSet<PRUser>();
        }
    
        public string PropertyManagerID { get; set; }
        public string PropertyManagerName { get; set; }
        public string PropertyManagerInitials { get; set; }
        public string PropertyManagerExtraInfo { get; set; }
        public string PropertyManagerAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRProperty> PRProperties { get; set; }
        public virtual PRUser PRUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRRenewal> PRRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUnit> PRUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRUser> PRUsers { get; set; }
    }
}
