//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRRenewal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRRenewal()
        {
            this.PRRenewalEmails = new HashSet<PRRenewalEmail>();
            this.PRRenewalStages = new HashSet<PRRenewalStage>();
        }
    
        public string RenewalID { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<decimal> OldRate { get; set; }
        public Nullable<decimal> NewRate { get; set; }
        public string SurveyID { get; set; }
        public string SurveyRequired { get; set; }
        public string UnitID { get; set; }
        public string CurrentStatus { get; set; }
        public string HOAApproval { get; set; }
        public string HOAStatus { get; set; }
        public string OwnerStatus { get; set; }
        public string PMStatus { get; set; }
        public Nullable<System.DateTime> HOADate { get; set; }
        public Nullable<System.DateTime> OwnerDate { get; set; }
        public Nullable<System.DateTime> PMDate { get; set; }
        public string PropertyManagerID { get; set; }
        public string OwnerID { get; set; }
        public string COP { get; set; }
        public string RenewalState { get; set; }
        public Nullable<System.DateTime> LastRenewal { get; set; }
        public Nullable<System.DateTime> NextRenewal { get; set; }
        public string Subsidy { get; set; }
        public string Survey125 { get; set; }
        public string AdobeID { get; set; }
        public string Renew { get; set; }
        public string Mtm { get; set; }
        public string PMAction { get; set; }
        public string SpecialProvisions { get; set; }
        public string RentersInsur { get; set; }
    
        public virtual PROwner PROwner { get; set; }
        public virtual PRPropertyManager PRPropertyManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRRenewalEmail> PRRenewalEmails { get; set; }
        public virtual PRUnit PRUnit { get; set; }
        public virtual PRSurvey PRSurvey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRRenewalStage> PRRenewalStages { get; set; }
    }
}
