//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRRenewalEmail
    {
        public string EmailsID { get; set; }
        public string RenewalID { get; set; }
        public string RecipientType { get; set; }
        public string EmailBody { get; set; }
        public System.DateTime DateSent { get; set; }
        public string Recipient { get; set; }
        public string RecipientID { get; set; }
    
        public virtual PRRenewal PRRenewal { get; set; }
    }
}
