//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRRenewalStage
    {
        public string StageID { get; set; }
        public string RenewalID { get; set; }
        public int Stage { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual PRRenewal PRRenewal { get; set; }
    }
}
