//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRSetting
    {
        public string SettingsID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string UserID { get; set; }
        public string ORSettingsID { get; set; }
        public string WASettingsID { get; set; }
        public string DateThresholdsID { get; set; }
    
        public virtual PRDateThreshold PRDateThreshold { get; set; }
        public virtual PRORSetting PRORSetting { get; set; }
        public virtual PRUser PRUser { get; set; }
        public virtual PRWASetting PRWASetting { get; set; }
    }
}
