//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRSurvey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRSurvey()
        {
            this.PRRenewals = new HashSet<PRRenewal>();
        }
    
        public string SurveyID { get; set; }
        public string AppfolioWorkOrderNo { get; set; }
        public string RazorSyncId { get; set; }
        public Nullable<System.DateTime> ScheduledDate { get; set; }
        public string SurveyStatus { get; set; }
        public string SurveyZip { get; set; }
        public string PropertyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRRenewal> PRRenewals { get; set; }
        public virtual PRSurvey PRSurveys1 { get; set; }
        public virtual PRSurvey PRSurvey1 { get; set; }
    }
}
