//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRTenant
    {
        public string TenantID { get; set; }
        public string TenantName { get; set; }
        public string UnitID { get; set; }
        public string TenantEmail { get; set; }
        public string TenantTags { get; set; }
        public Nullable<System.DateTime> TenantRentersInsurance { get; set; }
        public string PrimaryTenant { get; set; }
    
        public virtual PRUnit PRUnit { get; set; }
    }
}
