//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRUnit()
        {
            this.PRRenewals = new HashSet<PRRenewal>();
            this.PRTenants = new HashSet<PRTenant>();
        }
    
        public string UnitID { get; set; }
        public string PropertyID { get; set; }
        public string UnitAddress { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PropertyManagerID { get; set; }
        public string Tags { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> LastRenewal { get; set; }
        public string Unit { get; set; }
    
        public virtual PRProperty PRProperty { get; set; }
        public virtual PRPropertyManager PRPropertyManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRRenewal> PRRenewals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRTenant> PRTenants { get; set; }
    }
}
