//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community_Factor
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRWARateIncrease
    {
        public string WARateIncreaseID { get; set; }
        public string WASettingsID { get; set; }
        public int RateStart { get; set; }
        public Nullable<int> RateEnd { get; set; }
        public int Increase { get; set; }
    
        public virtual PRWASetting PRWASetting { get; set; }
    }
}
